// Format for @mathjax versions 3 and 4
// export const defaultMacros = {
//   // Greek letters
//   'uupsilon': '\\pmb{\\upsilon}',
//   'llambda': '\\pmb{\\lambda}',
//   'bbeta': '\\pmb{\\beta}',
//   'aalpha': '\\pmb{\\alpha}',
//   'zzeta': '\\pmb{\\zeta}',
//   'etaeta': '\\boldsymbol{\\eta}',
//   'xixi': '\\boldsymbol{\\xi}',
//   'ep': '\\boldsymbol{\\epsilon}',
//   'DEL': '\\boldsymbol{\\Delta}',
//   'PHI': '\\boldsymbol{\\Phi}',
//   'PI': '\\boldsymbol{\\Pi}',
//   'LAM': '\\boldsymbol{\\Lambda}',
//   'LAMm': '\\mathbb{L}',
//   'GAM': '\\boldsymbol{\\Gamma}',
//   'OMG': '\\boldsymbol{\\Omega}',
//   'SI': '\\boldsymbol{\\Sigma}',
//   'TH': '\\boldsymbol{\\Theta}',
//   'UPS': '\\boldsymbol{\\Upsilon}',
//   'XI': '\\boldsymbol{\\Xi}',
//
//   // Matrix/vector notation
//   'AA': '\\mathbf{A}', 'aa': '\\mathbf{a}',
//   'BB': '\\mathbf{B}', 'bb': '\\mathbf{b}',
//   'CC': '\\mathbf{C}', 'cc': '\\mathbf{c}',
//   'DD': '\\mathbf{D}', 'dd': '\\mathbf{d}',
//   'EE': '\\mathbf{E}', 'ee': '\\mathbf{e}',
//   'FF': '\\mathbf{F}', 'ff': '\\mathbf{f}',
//   'GG': '\\mathbf{G}', 'gg': '\\mathbf{g}',
//   'HH': '\\mathbf{H}', 'hh': '\\mathbf{h}',
//   'II': '\\mathbf{I}', 'ii': '\\mathbf{i}',
//   'IIm': '\\mathbf{I}',
//   'JJ': '\\mathbf{J}',
//   'KK': '\\mathbf{K}',
//   'LL': '\\mathbf{L}', 'll': '\\mathbf{l}',
//   'MM': '\\mathbf{M}', 'mm': '\\mathbf{m}',
//   'OO': '\\mathbf{O}',
//   'PP': '\\mathbf{P}', 'pp': '\\mathbf{p}',
//   'QQ': '\\mathbf{Q}', 'qq': '\\mathbf{q}',
//   'RR': '\\mathbf{R}', 'rr': '\\mathbf{r}',
//   'SS': '\\mathbf{S}',
//   'TT': '\\mathbf{T}',
//   'UU': '\\mathbf{U}', 'uu': '\\mathbf{u}',
//   'VV': '\\boldsymbol{V}', 'vv': '\\boldsymbol{v}',
//   'WW': '\\boldsymbol{W}', 'ww': '\\boldsymbol{w}',
//   'XX': '\\boldsymbol{X}', 'xx': '\\boldsymbol{x}',
//   'YY': '\\boldsymbol{Y}', 'yy': '\\boldsymbol{y}',
//   'ZZ': '\\mathbf{Z}', 'zz': '\\mathbf{z}',
//
//   // Special symbols
//   'zer': '\\boldsymbol{0}',
//
//   // Functions
//   'E': '\\mathrm{E}',
//   'EXy': '\\mathrm{E}_{\\mathbf{XY}}',
//   'N': '\\mathrm{N}',
//   'MVN': '\\mathrm{MVN}',
//   'chol': '\\mathrm{chol}',
//   'vec': '\\mathrm{vec}',
//   'var': '\\mathrm{Var}',
//   'cov': '\\mathrm{Cov}',
//   'diag': '\\mathrm{diag}',
//   'trace': '\\mathrm{trace}',
//   'dg': '\\mathrm{dg}',
//
//   // Alternative definitions
//   'Ab': '\\mathbf{D}', 'Aa': '\\mathbf{d}', 'Am': '\\boldsymbol{\\Pi}',
//   'Bb': '\\mathbf{J}', 'Ba': '\\mathbf{L}', 'Bm': '\\boldsymbol{\\Upsilon}',
//   'Ca': '\\Delta', 'Cb': '\\boldsymbol{\\Gamma}',
//   'Ub': '\\mathbf{C}', 'Ua': '\\mathbf{c}', 'Um': '\\boldsymbol{\\Upsilon}',
//   'Qb': '\\mathbf{G}', 'Qm': '\\mathbb{Q}',
//   'Rb': '\\mathbf{H}', 'Rm': '\\mathbb{R}',
//   'Zb': '\\mathbf{M}', 'Za': '\\mathbf{N}', 'Zm': '\\boldsymbol{\\Xi}',
//
//   // Tilde notation
//   'hatxt': '\\widetilde{\\mathbf{x}}_t',
//   'hatxtmt': '\\widetilde{\\mathbf{x}}_{t,t-1}',
//   'hatxone': '\\widetilde{\\mathbf{x}}_1',
//   'hatxzero': '\\widetilde{\\mathbf{x}}_0',
//   'hatxtm': '\\widetilde{\\mathbf{x}}_{t-1}',
//   'hatxQtm': '\\widetilde{\\mathbb{x}}_{t-1}',
//   'hatyt': '\\widetilde{\\mathbf{y}}_t',
//   'hatyone': '\\widetilde{\\mathbf{y}}_1',
//   'hatwt': '\\widetilde{\\mathbf{w}}_t',
//   'hatOt': '\\widetilde{\\mathbf{O}}_t',
//   'hatWt': '\\widehat{\\boldsymbol{W}}_t',
//   'hatWtp': '\\widehat{\\boldsymbol{W}}_{t+1}',
//   'hatwtp': '\\widehat{\\boldsymbol{w}}_{t+1}',
//   'hatVt': '\\widehat{\\boldsymbol{V}}_t',
//   'hatUtT': '\\widehat{\\boldsymbol{U}}_t^T',
//   'hatvt': '\\widehat{\\boldsymbol{v}}_t',
//   'hatPt': '\\widetilde{\\mathbf{P}}_t',
//   'hatUt': '\\widetilde{\\mathbf{U}}_t',
//   'hatPtm': '\\widetilde{\\mathbf{P}}_{t-1}',
//   'hatPQtm': '\\widetilde{\\mathbb{P}}_{t-1}',
//   'hatPttm': '\\widetilde{\\mathbf{P}}_{t,t-1}',
//   'hatPQttm': '\\widetilde{\\mathbb{P}}_{t,t-1}',
//   'hatPtmt': '\\widetilde{\\mathbf{P}}_{t-1,t}',
//   'hatVtT': '\\widetilde{\\boldsymbol{V}}_t^T',
//   'hatVtpT': '\\widetilde{\\boldsymbol{V}}_{t+1}^T',
//   'hatVtmT': '\\widetilde{\\boldsymbol{V}}_{t-1}^T',
//   'hatVtt': '\\widetilde{\\boldsymbol{V}}_t^t',
//   'hatStt': '\\widetilde{\\boldsymbol{S}}_t^t',
//   'hatStT': '\\widetilde{\\boldsymbol{S}}_t^T',
//   'hatVttm': '\\widetilde{\\boldsymbol{V}}_{t,t-1}',
//   'hatVttmT': '\\widetilde{\\boldsymbol{V}}_{t,t-1}^T',
//   'hatVttpT': '\\widetilde{\\boldsymbol{V}}_{t,t+1}^T',
//   'hatVtptT': '\\widetilde{\\boldsymbol{V}}_{t,t+1}^T',
//   'hatSttm': '\\widetilde{\\boldsymbol{S}}_{t,t-1}',
//   'hatVtmtT': '\\widetilde{\\boldsymbol{V}}_{t,t-1}^T',
//   'hatStmtT': '\\widetilde{\\boldsymbol{S}}_{t,t-1}^T',
//   'hatSttmT': '\\widetilde{\\boldsymbol{S}}_{t,t-1}^T',
//   'hatSttpT': '\\widetilde{\\boldsymbol{S}}_{t,t+1}^T',
//
//   // More complex notation
//   'hatxtT': '\\widetilde{\\boldsymbol{x}}_t^T',
//   'hatxtpT': '\\widetilde{\\boldsymbol{x}}_{t+1}^T',
//   'hatxtt': '\\widetilde{\\boldsymbol{x}}_t^{t}',
//   'hatxttm': '\\widetilde{\\boldsymbol{x}}_t^{t-1}',
//   'hatxtmT': '\\widetilde{\\boldsymbol{x}}_{t-1}^T',
//   'hatxtmt1': '\\widetilde{\\boldsymbol{x}}_{t-1}^{t-1}',
//   'hatxtpt1': '\\widetilde{\\boldsymbol{x}}_{t+1}^{t-1}',
//
//   // Check/overline notation
//   'checkWt': '\\overline{\\boldsymbol{W}}_t',
//   'checkWtp': '\\overline{\\boldsymbol{W}}_{t+1}',
//   'checkwt': '\\overline{\\boldsymbol{w}}_t',
//   'checkwtp': '\\overline{\\boldsymbol{w}}_{t+1}',
//   'checkvt': '\\overline{\\boldsymbol{v}}_t',
//   'checkvtp': '\\overline{\\boldsymbol{v}}_{t+1}',
//   'checkVtp': '\\overline{\\boldsymbol{V}}_{t+1}',
//   'checkVt': '\\overline{\\boldsymbol{V}}_t',
//
//   // Dot notation
//   'dotvt': '\\dot{\\boldsymbol{v}}_t',
//   'dotvtp': '\\dot{\\boldsymbol{v}}_{t+1}',
//   'dotVtp': '\\dot{\\boldsymbol{V}}_{t+1}',
//   'dotVt': '\\dot{\\boldsymbol{V}}_t',
//   'YYr': '\\dot{\\boldsymbol{Y}}',
//   'yyr': '\\dot{\\boldsymbol{y}}',
//   'aar': '\\dot{\\mathbf{a}}',
//   'ZZr': '\\dot{\\mathbf{Z}}',
//   'RRr': '\\dot{\\mathbf{R}}',
//
//   // Misc
//   'IR': '\\nabla',
//   'R': 'R',
//   'Ss': '\\mathbf{S}'
// };

// Format for mathjax-full
export const defaultMacros = {
  // Greek letters
  uupsilon: '\\pmb{\\upsilon}',
  llambda: '\\pmb{\\lambda}',
  bbeta: '\\pmb{\\beta}',
  aalpha: '\\pmb{\\alpha}',
  zzeta: '\\pmb{\\zeta}',
  etaeta: '\\boldsymbol{\\eta}',
  xixi: '\\boldsymbol{\\xi}',
  ep: '\\boldsymbol{\\epsilon}',
  DEL: '\\boldsymbol{\\Delta}',
  PHI: '\\boldsymbol{\\Phi}',
  PI: '\\boldsymbol{\\Pi}',
  LAM: '\\boldsymbol{\\Lambda}',
  LAMm: '\\mathbb{L}',
  GAM: '\\boldsymbol{\\Gamma}',
  OMG: '\\boldsymbol{\\Omega}',
  SI: '\\boldsymbol{\\Sigma}',
  TH: '\\boldsymbol{\\Theta}',
  UPS: '\\boldsymbol{\\Upsilon}',
  XI: '\\boldsymbol{\\Xi}',

  // Matrix/vector notation
  AA: '\\mathbf{A}',
  aa: '\\mathbf{a}',
  BB: '\\mathbf{B}',
  bb: '\\mathbf{b}',
  CC: '\\mathbf{C}',
  cc: '\\mathbf{c}',
  DD: '\\mathbf{D}',
  dd: '\\mathbf{d}',
  EE: '\\mathbf{E}',
  ee: '\\mathbf{e}',
  FF: '\\mathbf{F}',
  ff: '\\mathbf{f}',
  GG: '\\mathbf{G}',
  gg: '\\mathbf{g}',
  HH: '\\mathbf{H}',
  hh: '\\mathbf{h}',
  II: '\\mathbf{I}',
  ii: '\\mathbf{i}',
  IIm: '\\mathbf{I}',
  JJ: '\\mathbf{J}',
  KK: '\\mathbf{K}',
  LL: '\\mathbf{L}',
  ll: '\\mathbf{l}',
  MM: '\\mathbf{M}',
  mm: '\\mathbf{m}',
  OO: '\\mathbf{O}',
  PP: '\\mathbf{P}',
  pp: '\\mathbf{p}',
  QQ: '\\mathbf{Q}',
  qq: '\\mathbf{q}',
  RR: '\\mathbf{R}',
  rr: '\\mathbf{r}',
  SS: '\\mathbf{S}',
  TT: '\\mathbf{T}',
  UU: '\\mathbf{U}',
  uu: '\\mathbf{u}',
  VV: '\\boldsymbol{V}',
  vv: '\\boldsymbol{v}',
  WW: '\\boldsymbol{W}',
  ww: '\\boldsymbol{w}',
  XX: '\\boldsymbol{X}',
  xx: '\\boldsymbol{x}',
  YY: '\\boldsymbol{Y}',
  yy: '\\boldsymbol{y}',
  ZZ: '\\mathbf{Z}',
  zz: '\\mathbf{z}',

  // Special symbols
  zer: '\\boldsymbol{0}',

  // Functions
  E: '\\mathrm{E}',
  EXy: '\\mathrm{E}_{\\mathbf{XY}}',
  N: '\\mathrm{N}',
  MVN: '\\mathrm{MVN}',
  chol: '\\mathrm{chol}',
  vec: '\\mathrm{vec}',
  var: '\\mathrm{Var}',
  cov: '\\mathrm{Cov}',
  diag: '\\mathrm{diag}',
  trace: '\\mathrm{trace}',
  dg: '\\mathrm{dg}',

  // Alternative definitions
  Ab: '\\mathbf{D}',
  Aa: '\\mathbf{d}',
  Am: '\\boldsymbol{\\Pi}',
  Bb: '\\mathbf{J}',
  Ba: '\\mathbf{L}',
  Bm: '\\boldsymbol{\\Upsilon}',
  Ca: '\\Delta',
  Cb: '\\boldsymbol{\\Gamma}',
  Ub: '\\mathbf{C}',
  Ua: '\\mathbf{c}',
  Um: '\\boldsymbol{\\Upsilon}',
  Qb: '\\mathbf{G}',
  Qm: '\\mathbb{Q}',
  Rb: '\\mathbf{H}',
  Rm: '\\mathbb{R}',
  Zb: '\\mathbf{M}',
  Za: '\\mathbf{N}',
  Zm: '\\boldsymbol{\\Xi}',

  // Tilde notation
  hatxt: '\\widetilde{\\mathbf{x}}_t',
  hatxtmt: '\\widetilde{\\mathbf{x}}_{t,t-1}',
  hatxone: '\\widetilde{\\mathbf{x}}_1',
  hatxzero: '\\widetilde{\\mathbf{x}}_0',
  hatxtm: '\\widetilde{\\mathbf{x}}_{t-1}',
  hatxQtm: '\\widetilde{\\mathbb{x}}_{t-1}',
  hatyt: '\\widetilde{\\mathbf{y}}_t',
  hatyone: '\\widetilde{\\mathbf{y}}_1',
  hatwt: '\\widetilde{\\mathbf{w}}_t',
  hatOt: '\\widetilde{\\mathbf{O}}_t',
  hatWt: '\\widehat{\\boldsymbol{W}}_t',
  hatWtp: '\\widehat{\\boldsymbol{W}}_{t+1}',
  hatwtp: '\\widehat{\\boldsymbol{w}}_{t+1}',
  hatVt: '\\widehat{\\boldsymbol{V}}_t',
  hatUtT: '\\widehat{\\boldsymbol{U}}_t^T',
  hatvt: '\\widehat{\\boldsymbol{v}}_t',
  hatPt: '\\widetilde{\\mathbf{P}}_t',
  hatUt: '\\widetilde{\\mathbf{U}}_t',
  hatPtm: '\\widetilde{\\mathbf{P}}_{t-1}',
  hatPQtm: '\\widetilde{\\mathbb{P}}_{t-1}',
  hatPttm: '\\widetilde{\\mathbf{P}}_{t,t-1}',
  hatPQttm: '\\widetilde{\\mathbb{P}}_{t,t-1}',
  hatPtmt: '\\widetilde{\\mathbf{P}}_{t-1,t}',
  hatVtT: '\\widetilde{\\boldsymbol{V}}_t^T',
  hatVtpT: '\\widetilde{\\boldsymbol{V}}_{t+1}^T',
  hatVtmT: '\\widetilde{\\boldsymbol{V}}_{t-1}^T',
  hatVtt: '\\widetilde{\\boldsymbol{V}}_t^t',
  hatStt: '\\widetilde{\\boldsymbol{S}}_t^t',
  hatStT: '\\widetilde{\\boldsymbol{S}}_t^T',
  hatVttm: '\\widetilde{\\boldsymbol{V}}_{t,t-1}',
  hatVttmT: '\\widetilde{\\boldsymbol{V}}_{t,t-1}^T',
  hatVttpT: '\\widetilde{\\boldsymbol{V}}_{t,t+1}^T',
  hatVtptT: '\\widetilde{\\boldsymbol{V}}_{t,t+1}^T',
  hatSttm: '\\widetilde{\\boldsymbol{S}}_{t,t-1}',
  hatVtmtT: '\\widetilde{\\boldsymbol{V}}_{t,t-1}^T',
  hatStmtT: '\\widetilde{\\boldsymbol{S}}_{t,t-1}^T',
  hatSttmT: '\\widetilde{\\boldsymbol{S}}_{t,t-1}^T',
  hatSttpT: '\\widetilde{\\boldsymbol{S}}_{t,t+1}^T',

  // More complex notation
  hatxtT: '\\widetilde{\\boldsymbol{x}}_t^T',
  hatxtpT: '\\widetilde{\\boldsymbol{x}}_{t+1}^T',
  hatxtt: '\\widetilde{\\boldsymbol{x}}_t^{t}',
  hatxttm: '\\widetilde{\\boldsymbol{x}}_t^{t-1}',
  hatxtmT: '\\widetilde{\\boldsymbol{x}}_{t-1}^T',
  hatxtmt1: '\\widetilde{\\boldsymbol{x}}_{t-1}^{t-1}',
  hatxtpt1: '\\widetilde{\\boldsymbol{x}}_{t+1}^{t-1}',

  // Check/overline notation
  checkWt: '\\overline{\\boldsymbol{W}}_t',
  checkWtp: '\\overline{\\boldsymbol{W}}_{t+1}',
  checkwt: '\\overline{\\boldsymbol{w}}_t',
  checkwtp: '\\overline{\\boldsymbol{w}}_{t+1}',
  checkvt: '\\overline{\\boldsymbol{v}}_t',
  checkvtp: '\\overline{\\boldsymbol{v}}_{t+1}',
  checkVtp: '\\overline{\\boldsymbol{V}}_{t+1}',
  checkVt: '\\overline{\\boldsymbol{V}}_t',

  // Dot notation
  dotvt: '\\dot{\\boldsymbol{v}}_t',
  dotvtp: '\\dot{\\boldsymbol{v}}_{t+1}',
  dotVtp: '\\dot{\\boldsymbol{V}}_{t+1}',
  dotVt: '\\dot{\\boldsymbol{V}}_t',
  YYr: '\\dot{\\boldsymbol{Y}}',
  yyr: '\\dot{\\boldsymbol{y}}',
  aar: '\\dot{\\mathbf{a}}',
  ZZr: '\\dot{\\mathbf{Z}}',
  RRr: '\\dot{\\mathbf{R}}',

  // Misc
  IR: '\\nabla',
  R: 'R',
  Ss: '\\mathbf{S}'
};
